### ISSUE TITLE
B3LYP using VWN3

### ISSUE THREAD

**Issue by mbanck** [cmsi/smash#4]
Most popular QM codes use the VWN3 correlation functional, not VWN5, because Gaussian went ahead and implemented that even if VWN5 is recommended. So in order to better compare results between codes, it would be good if VWN3 could at least be provided as an option.

**Comment by ishimura** [comment]
Thank you for your comment.
The VWN3 functional is used from Version 2.0.0, and "method=B3LYP5" is added for the VWN5.
