### ISSUE TITLE
README should be updated to reflect RHF-MP2 gradients

### ISSUE THREAD

**Issue by mbanck** [cmsi/smash#5]
If I understand correctly, closed-shell MP2 gradients are available in the latest release, so the README should be updated to reflect this capability. Right now it says 

```It is currently capable of energy, analytical gradient, and geometry optimization calculations of Hartree-Fock theory and Density Functional Theory (DFT), and energy calculations of Second-order Moller-Plesset (MP2) perturbation theory.```

**Comment by ishimura** [comment]
README was updated.
